[global]
# The 'From' address to put on posts. If you change this then try to resume
# a posting, many clients will get confused.
From="Test <teSPAMst@examNOSPAMple.com>"

# Default group to post files to. You can specify multiple groups by separating
# then with a comma, e.g. "alt.binaries.test,alt.binaries.test.yenc".
DefaultGroup="alt.binaries.test.yenc"

# String to place at the start of every subject line - a space will be added.
#SubjectPrefix=[OINK]

# Size of each yEnc chunk in bytes. This should be fine unless your Usenet
# server is weird and complains about articles being too large.
ArticleSize=768000

# Chunk size in bytes to use when writing articles to a connection. You may
# need to increase this on very high speed connections, who knows.
ChunkSize=10240

# A server definition. You can have multiple if you like that sort of thing.
[[server]]
Name="pants"
Address="testserver.int"
Address="us.newsdemon.com"
Port=563

# Leave password blank if you only need a username. Leave both blank if you
# don't need either.
Username="testuser"
Password="topsecret"

# Number of simultaneous connections. You pretty much just have to test with
# varying numbers until you hit a reasonable amount for your server and
# internet connection.
Connections=1

# Encryption
TLS=true

# Ignore SSL errors like self-signed certificates. This is a pretty bad idea.
InsecureSSL=false
